### PR TITLE
Logrotate msvc minimal kjell input

### PR DESCRIPTION
**Pull request by KjellKod**
Hi, 

I've refactored out the anonymous namespace in the ipp file to its own namespace instance. This makes it possible to use the utility functions in unit tests. 

I added a test to verify that the files  **were not** deleted when expired, just like you said. Then I corrected it (as you suggested) and it worked great. 

I pulled down your pull request and merged it with mine. Unfortunately that gave a few compilation errors. 
The last compilation error seems to have something to do with the ifdefs.  I removed some of the ifdef's but it still doesn't work. 

Please take a peek at it, any idea why we get this error?

(OSX)
```
Undefined symbols for architecture x86_64:
  "LogRotateUtility::expireArchives(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned long)", referenced from:
      LogRotateHelper::rotateLog() in libg3logrotate.a(LogRotate.cpp.o)
  "LogRotateUtility::getLogFilesInDirectory(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      RotateFileTest_rotateAndExpireOldLogs_Test::TestBody() in RotateFileTest.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [UnitTestRunner] Error 1
make[1]: *** [CMakeFiles/UnitTestRunner.dir/all] Error 2
make: *** [all] Error 2
```

### CODE REVIEW

**Comment by cstamatopoulos** [comment]
I went ahead and merged it since I though all was OK after the addition of some missing includes.
Then I compiled the shared version and got the same  errors.
It is a linker error for a symbol that cannot be found. 
Looking into it but I definitely was not getting this error before.

**Comment by cstamatopoulos** [comment]
Here you go
void expireArchives(const **std::string&** dir, const std::string& app_name, unsigned long max_log_count);
   void expireArchives(const **std::string** dir, const std::string& app_name, unsigned long max_log_count)

**Comment by KjellKod** [comment]
Awesome. Thanks.

Did you see the unit test that I added? It confirmed your bug report

**Comment by cstamatopoulos** [comment]
Yes I did.
I was testing it myself and that is how I saw it. I fixed it and confirm
that all was good but I did not write a proper test case.

There is only one test that I could not run due to compilation error.
Undefined symbol again.
It seems that this function only has a declaration !

std::map<long, std::string> getLogFilesInDirectory(const std::string& dir,
const std::string& app_name);

Did you forget to push ?

**Comment by cstamatopoulos** [comment]
It seems that you removed it with commit 
"removing ifdef for now"

**Comment by KjellKod** [comment]
Thanks. Are you good or should I do a pull request to your pull request

**Comment by KjellKod** [comment]
?

**Comment by cstamatopoulos** [comment]
Depends how you want to sort it out.

1. Keep it as it is an just add something local to the unit test since that is the only place it is used ?
2. Change it as you had it before, with a function that gets the log files and is used both in the unit test as well as the expireArchives function.

Not sure what you were trying to refactor there.

**Comment by KjellKod** [comment]
see my new pull request to your branch

**Pull request merged**
